=== alliedtelesis/apteryx-xml/apteryx.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="https://github.com/alliedtelesis/apteryx"
	xmlns="https://github.com/alliedtelesis/apteryx"
	elementFormDefault="qualified">
	<xs:element name="VALUE">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required" />
			<xs:attribute name="value" type="xs:string" use="required" />
			<xs:attribute name="help" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="PROVIDE">
	</xs:element>
	<xs:element name="INDEX">
	</xs:element>
	<xs:element name="WATCH">
	</xs:element>
	<xs:element name="REFRESH">
	</xs:element>
	<xs:element name="NODE">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="NODE" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="VALUE" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="WATCH" minOccurs="0" maxOccurs="1" />
				<xs:element ref="PROVIDE" minOccurs="0" maxOccurs="1" />
				<xs:element ref="INDEX" minOccurs="0" maxOccurs="1" />
				<xs:element ref="REFRESH" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[^_\s]*"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="default" type="xs:string" use="optional" />
			<xs:attribute name="pattern" type="xs:string" use="optional" />
			<xs:attribute name="range" type="xs:string" use="optional" />
			<xs:attribute name="key" type="xs:string" use="optional" />
			<xs:attribute name="unique" type="xs:string" use="optional" />
			<xs:attribute name="help" type="xs:string" use="optional" />
			<xs:attribute name="mode" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="(p|x|hx|[rhwc]{1,4})"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="SCRIPT">
	</xs:element>
	<xs:element name="MODULE">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="SCRIPT" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="NODE" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="model" type="xs:string" use="optional" />
			<xs:attribute name="namespace" type="xs:string" use="optional" />
			<xs:attribute name="prefix" type="xs:string" use="optional" />
			<xs:attribute name="organization" type="xs:string" use="optional" />
			<xs:attribute name="version" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== alliedtelesis/apteryx-xml/models/xlat_test.xml
<?xml version='1.0' encoding='UTF-8'?>
<MODULE xmlns="http://test.com/ns/yang/xlat-testing"
    xmlns:xlat-test="http://test.com/ns/yang/xlat-testing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://github.com/alliedtelesis/apteryx-xml https://github.com/alliedtelesis/apteryx-xml/releases/download/v1.2/apteryx.xsd"
    model="xlat-test" organization="Test Ltd" version="2023-01-01">
    <NODE name="xlat-test" help="This is a test node">
        <NODE name="xlat-animals">
            <NODE name="xlat-animal" help="This is a list of animals">
                <NODE name="*" help="The animal entry with key name">
                    <NODE name="name" mode="rw" help="This is the name of the animal" />
                    <NODE name="type" mode="rw" default="big" help="This is the type of the animal">
                        <VALUE name="fast" value="3" />
                        <VALUE name="slow" value="4" />
                    </NODE>
                    <NODE name="colour" mode="rw" help="This is the colour of the animal" />
                    <NODE name="food">
                        <NODE name="*" help="This is a list of food">
                            <NODE name="name" mode="rw" help="Food name" />
                            <NODE name="type" mode="rw" help="Food type" />
                        </NODE>
                    </NODE>
                    <NODE name="toys">
                        <NODE name="toy" help="This is a leaf list of toys">
                            <NODE name="*" mode="rw" help="List of toys" />
                        </NODE>
                    </NODE>
                </NODE>
            </NODE>
        </NODE>
    </NODE>
</MODULE>

=== alliedtelesis/apteryx-xml/models/test4:rpc.xml
<?xml version='1.0' encoding='UTF-8'?>
<MODULE xmlns="http://test.com/ns/yang/testing-4"
        xmlns:test="http://test.com/ns/yang/testing"
        xmlns:t4="http://test.com/ns/yang/testing-4"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://github.com/alliedtelesis/apteryx-xml https://github.com/alliedtelesis/apteryx-xml/releases/download/v1.2/apteryx.xsd"
        model="testing-4" organization="Test 4 Ltd" version="2024-02-01">
  <NODE name="test" help="This is a test node in the testing-4 namespace">
    <NODE name="state" help="State">
      <NODE name="age" mode="r" help="a string"/>
      <NODE name="history" help="List of last reset times">
        <NODE name="*" help="Reset time" range="0..4294967295"/>
      </NODE>
      <NODE name="reset" mode="rwx" help="Reset state">
        <NODE name="input" help="Input parameters">
          <NODE name="delay" mode="w" help="Number of seconds to wait before starting the reset" range="0..4294967295"/>
        </NODE>
        <NODE name="output" help="Output parameters">
          <NODE name="delay" mode="r" help="Last number of seconds waited before reset" range="0..4294967295"/>
        </NODE>
      </NODE>
      <NODE name="get-last-reset-time" mode="rwx" help="Retrieve the last interface reset time">
        <NODE name="output" help="Output parameters">
          <NODE name="last-reset" mode="r" help="Time of the last reset" range="0..4294967295"/>
          <NODE name="history" help="List of last reset times">
            <NODE name="*" help="Last reset time" range="0..4294967295"/>
          </NODE>
        </NODE>
      </NODE>
      <NODE name="get-reset-history" mode="rwx" help="Retrieve the history of resets">
        <NODE name="output" help="Output parameters">
          <NODE name="last-reset" mode="r" help="Time of the last reset" range="0..4294967295"/>
          <NODE name="history" help="List of last reset times">
            <NODE name="*" help="Last reset time" range="0..4294967295"/>
          </NODE>
        </NODE>
      </NODE>
      <NODE name="users" help="This is a list of users">
        <NODE name="*" help="The user entry with key name">
          <NODE name="name" mode="rw" help="This is the name of the user"/>
          <NODE name="age" mode="rw" help="Age of the user" range="0..4294967295"/>
          <NODE name="_" mode="rwx" help="get/add/delete users">
            <NODE name="input" help="Input parameters">
              <NODE name="name" mode="w" help="User name"/>
              <NODE name="age" mode="w" help="User age" range="0..4294967295"/>
            </NODE>
            <NODE name="output" help="Input parameters">
              <NODE name="users" help="This is a list of users">
                <NODE name="*" help="The user entry with key name">
                  <NODE name="name" mode="r" help="User name"/>
                  <NODE name="age" mode="r" help="User age" range="0..4294967295"/>
                </NODE>
              </NODE>
            </NODE>
          </NODE>
          <NODE name="set-age" mode="rwx" help="Set the users age">
            <NODE name="input" help="Input parameters">
              <NODE name="age" mode="w" help="New age" range="0..4294967295"/>
            </NODE>
          </NODE>
        </NODE>
      </NODE>
    </NODE>
  </NODE>
  <test:NODE name="operations" help="Container for all operation resources.">
    <NODE name="reboot" mode="rwx" help="Reboot operation.">
      <NODE name="input" help="Input parameters">
        <NODE name="delay" mode="w" help="Number of seconds to wait before initiating the reboot operation." range="0..4294967295"/>
        <NODE name="message" mode="w" help="Log message to display when reboot is started."/>
        <NODE name="language" mode="w" help="Language identifier string."/>
      </NODE>
    </NODE>
    <NODE name="get-reboot-info" mode="rwx" help="Retrieve parameters used in the last reboot operation.">
      <NODE name="output" help="Output parameters">
        <NODE name="reboot-time" mode="r" help="The 'delay' parameter used in the last reboot operation." range="0..4294967295"/>
        <NODE name="message" mode="r" help="The 'message' parameter used in the last reboot operation."/>
        <NODE name="language" mode="r" help="The 'language' parameter used in the last reboot operation."/>
      </NODE>
    </NODE>
    <NODE name="get-rpcs" mode="rwx" help="Retrieve the list of all RPCs">
      <NODE name="output" help="Output parameters">
        <NODE name="paths" help="List of RPCs">
          <NODE name="*" help="An RPC">
            <NODE name="path" mode="r" help="RPC path"/>
            <NODE name="methods" help="List of methods this RPC supports">
              <NODE name="*" mode="r" help="A method" pattern="POST|GET|PUT|PATCH|DELETE|HEAD|OPTIONS"/>
            </NODE>
          </NODE>
        </NODE>
      </NODE>
    </NODE>
  </test:NODE>
</MODULE>

=== alliedtelesis/apteryx-xml/models/test2:test2.xml
<?xml version='1.0' encoding='UTF-8'?>
<MODULE xmlns="http://test.com/ns/yang/testing-2" 
        xmlns:t2="http://test.com/ns/yang/testing-2"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://github.com/alliedtelesis/apteryx-xml https://github.com/alliedtelesis/apteryx-xml/releases/download/v1.2/apteryx.xsd"
        model="testing-2" organization="Test 2 Ltd" version="2023-02-01">
  <NODE name="test" help="This is a test node">
    <NODE name="settings" help="Settings">
      <NODE name="priority" mode="rw" help="integer" range="1..5"/>
      <NODE name="users" help="This is a list of users">
        <NODE name="*" help="The user entry with key name">
          <NODE name="name" mode="rw" help="This is the name of the user"/>
        </NODE>
      </NODE>
    </NODE>
    <NODE name="state" help="State">
      <NODE name="priority" mode="r" help="integer"/>
    </NODE>
  </NODE>
</MODULE>
